#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("src")

require 'rubygems'
require 'optparse'
require "application"

Version = "0.0.1"

user_args = {}
opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage example: ruby bofrev.rb
\nFor additional information please visit bofrev's github repository:\nhttps://github.com/simplay/bofrev"
  opt.separator ""

  opt.on("-d", "--debug d", Integer, "Running mode: nil normal, 1 w/e music, 2 also w/e game thread") do |debug|
    user_args[:debug] = debug
  end

  opt.on("-g", "--game g", Integer, "Desired Game to Play: nil normal, 1 Tetris") do |game|
    user_args[:game] = game
  end

  opt.on("-m", "--multiplayer g", Integer, "Desired Game to Play: 0 Single-player, 1 Multiplayer Client, 2 Multiplayer Server") do |multiplayer|
    user_args[:multiplayer] = multiplayer
  end

  opt.on_tail("-h", "--help", "Show this message") do
    puts opt
    exit
  end
  opt.on_tail("--version", "Show version") do
    puts "bofrev #{Version}"
    exit
  end
end
begin
  opt_parser.parse!
rescue OptionParser::MissingArgument
  puts "Incorrect input argument(s) passed\n"
  puts opt_parser.help
  exit
end

Application.new(user_args)
